version: '1'
services:
  myreptile:
    build: ./reptile
    depends_on:
      - mydb
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "3m"
        max-file: "1"

  myweb:
    build: ./Web
    ports:
      - 5000:5000
    depends_on:
      - mydb
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "3m"
        max-file: "1"

  mydb:
    build: ./MariaDb
    ports:
      - 3306:3306
    volumes:
      - ./MariaDb/data/:/var/lib/mysql/
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "3m"
        max-file: "1"

  mynginx:
    build: ./Nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Nginx/Inside/:/usr/local/nginx/
    depends_on:
      - myweb
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "3m"
        max-file: "1"