name: ssh-deploy
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/**'
      - '开发文档/**'
      - '.gitignore'
      - 'README.md'
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '.github/**'
      - '开发文档/**'
      - '.gitignore'
      - 'README.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: testdeploy
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      env:
        LASTSSH: "Doing something after copying"
      with:
        host: ${{ secrets.ALYHOST }}
        user: ${{ secrets.ALYUSER }}
        pass: ${{ secrets.ALYPASS }}
        scp: |
          . => /home/dfsr/tmp/
        last_ssh: |
          echo $LASTSSH 
          cd /home/dfsr/
          bash deploy.sh
