name: testcode
on:
    push:
        branches:
          - "alpha"
        paths-ignore:
          - '.github/**'
          - '开发文档/**'
          - '.gitignore'
          - 'README.md'
    pull_request:
        branches:
          - "alpha"
        paths-ignore:
          - '.github/**'
          - '开发文档/**'
          - '.gitignore'
          - 'README.md'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: composetest
          run: |
            docker compose up

